### ISSUE TITLE
Builder methods child and attr move self

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#124]
Is it possible to change this methods to borrow and return a mut reference to self. To borrow self instead of moving it? Would this change things a lot?
```rust
pub fn child(mut self, child: Node<'a>) -> Self {
        self.children.push(child);
        self
    }
```

**Comment by fitzgen** [comment]
Some of the methods change the type parameters (eg changing children to a fixed size array) and therefore must take self. This particular method uses the same conventions because it is good to be consistent.

**Comment by bestia-dev** [comment]
Consistency is a must here. It is difficult or impossible or non-practical to mix methods that move and methods that borrow.  
I have rewritten my function to move the ElementBuilder. The code does not look so nice as borrowing, but it works well with other functions/methods.  
Now I have a new question in my head: is it faster to move or to borrow in the example of the ElementBuilder?   
Just for info, to have details what I'm working on:
I want to make a html templating for dodrio. I read a simple fragment of html and use ElementBuilder to create a Node. The first attempt without advanced features:
work in progress: <https://github.com/LucianoBestia/dodrio_templating>
```rust
/// Recursive function to fill the tree with a node.  
/// Moves & Returns ElementBuilder or error.  
fn fill_element_builder<'a>(
    pp: &mut ReaderForMicroXml,
    mut element: ElementBuilder<
        'a,
        bumpalo::collections::Vec<'a, Listener<'a>>,
        bumpalo::collections::Vec<'a, Attribute<'a>>,
        bumpalo::collections::Vec<'a, Node<'a>>,
    >,
    bump: &'a Bump,
) -> Result<
    ElementBuilder<
        'a,
        bumpalo::collections::Vec<'a, Listener<'a>>,
        bumpalo::collections::Vec<'a, Attribute<'a>>,
        bumpalo::collections::Vec<'a, Node<'a>>,
    >,
    String,
> {
    loop {
        match pp.read_event() {
            Event::StartElement(name) => {
                //construct a child element and fill it (recursive)
                let name = bumpalo::format!(in bump, "{}",name).into_bump_str();
                let mut child_element = ElementBuilder::new(bump, name);
                child_element = fill_element_builder(pp, child_element, bump)?;
                element = element.child(child_element.finish());
            }
            Event::Attribute(name, value) => {
                let name = bumpalo::format!(in bump, "{}",name).into_bump_str();
                let value = bumpalo::format!(in bump, "{}",value).into_bump_str();
                element = element.attr(name, value);
            }
            Event::TextNode(txt) => {
                let txt = bumpalo::format!(in bump, "{}",txt).into_bump_str();
                element = element.child(text(txt));
            }
            Event::EndElement(_name) => {
                // TODO: test if the element name is correct
                return Ok(element);
            }
            Event::Error(error_msg) => {
                return Err(format!("{}", error_msg));
            }
            Event::Eof => {
                return Ok(element);
            }
        }
    }
}
```

**Comment by fitzgen** [comment]
>  Now I have a new question in my head: is it faster to move or to borrow in the example of the ElementBuilder?

In a world where both are options, borrows are probably faster in practice because moves require LLVM to figure out that all the stack slots for each moved value have distinct live regions and collapse them into the same space.

**Comment by bestia-dev** [comment]
I see in you code you use #inline. Does it mean there is no move at all? I am just learning.
