### ISSUE TITLE
dispatch_event failed

### ISSUE THREAD

**Issue by extraymond** [fitzgen/dodrio#138]
Greetings. I was trying to use web_sys::EventTarget to send custom event. And it failed with the following code.

```rust
.on("click", move |_, _, e| {

    let target: web_sys::EventTarget = e.current_target().unwrap();
    let event = web_sys::Event::new("hey").unwrap();
    target.dispatch_event(&event).unwrap();
})
.on("hey", |_, _, _| {
    log::info!("i got heyed!!!");
})
```

The error trace:

```
panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1188:5

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@http://127.0.0.1:8000/wasm-bindgen-test:559:23
console_error_panic_hook::Error::new::hf554e6f5eb6fb1b1@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5206]:0x15819c
console_error_panic_hook::hook_impl::hee1fff08d7db4329@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[819]:0xb75ee
console_error_panic_hook::hook::h5c34a5c9072e6707@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5659]:0x15f04f
core::ops::function::Fn::call::hda110851ec8d5d65@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[5243]:0x158bb8
std::panicking::rust_panic_with_hook::h4e529e530989255b@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1336]:0xe06c1
rust_begin_unwind@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[3258]:0x12ea29
core::panicking::panic_fmt::h83dd057ea462878e@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[6341]:0x168403
core::result::unwrap_failed::h6d70f69438bf9954@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2821]:0x122228
core::result::Result<T,E>::expect::h06c7e073675d0e5c@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1349]:0xe1441
core::cell::RefCell<T>::borrow_mut::h78421ba0e9e39648@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[2400]:0x11404b
dodrio::events::EventsRegistry::new::{{closure}}::hd911a19e4fad900a@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[267]:0x6ae84
<dyn core::ops::function::Fn<(A, B, C)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h7a13cc7fc1060c19@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[980]:0xc5e1a
__wbg_adapter_26@http://127.0.0.1:8000/wasm-bindgen-test:214:10
real@http://127.0.0.1:8000/wasm-bindgen-test:1016:28
initEventsTrampoline/this.eventHandler@http://127.0.0.1:8000/snippets/dodrio-fb10e775fcadd85a/js/change-list-interpreter.js:374:17
init/imports.wbg.__widl_f_dispatch_event_EventTarget@http://127.0.0.1:8000/wasm-bindgen-test:735:43
web_sys::EventTarget::dispatch_event::h5c69e1a8d00a5014@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[873]:0xbc80b
<dodrio_ext::tests::test_original::Hello as dodrio::render::Render>::render::{{closure}}::h68f0951748cab627@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[900]:0xbef25
core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call::h94f90d2bf7912152@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[1592]:0xeff59
dodrio::events::EventsRegistry::new::{{closure}}::hd911a19e4fad900a@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[267]:0x6af4d
<dyn core::ops::function::Fn<(A, B, C)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h7a13cc7fc1060c19@http://127.0.0.1:8000/wasm-bindgen-test_bg.wasm:wasm-function[980]:0xc5e1a
__wbg_adapter_26@http://127.0.0.1:8000/wasm-bindgen-test:214:10
real@http://127.0.0.1:8000/wasm-bindgen-test:1016:28
initEventsTrampoline/this.eventHandler@http://127.0.0.1:8000/snippets/dodrio-fb10e775fcadd85a/js/change-list-interpreter.js:374:17
```

Is this because every time we send mutation into the bump arena, which controls and mutate an actual HtmlElement, it either get rebuild or patched so that the event target is no longer the same? Therefore trying to obtain the event_target from the web_sys::Event won't get us the correct address. And the listener on the dodrio::div can't receive calls too because the event_listener is actually registered in the element inside the bump arena?

I tried to call obtain the element by element_select_by_id and it emits the same error as above.
Would like to know if there's a proper way to setup custom event listener(other than standard dom events).

**Comment by extraymond** [comment]
I tried setting up the event listener after starting the dodrio component by manually setting an id for the element and send events via that element. 

This works but seems to create friction compared to the original component design, since now we might need to manually create id's and make sure they don't conflict with each other if more than one components are in used.

**Comment by fitzgen** [comment]
Unfortunately, this is expected behavior because of the way that refcells are used right now. The `RootRender` goes into one big refcell that is borrowed during each render tick / event handler. This saves users from needing to add refcells themselves. The trade off is that certain activities need to "await a lock" on the `RootRender`. An async lock might in fact be a better model than a refcell here.

Anyways, you should be able to make it work by waiting till the next tick of either the event loop or micro-task queue. This is what `VdomWeak::with_component` does, for example: https://github.com/fitzgen/dodrio/blob/master/src/vdom.rs#L396-L413 We could also probably add a similar helper for event dispatching, and maybe even catch-and-delay events that happen during other events. Would need to think about this more.

**Comment by extraymond** [comment]
Thanks for the info! I will take a look at that.

Currently I'm using a msg stream to gather events and call Vdom.render if it's a UI related event, otherwise it'll just mutate the data model without calling render. So I can trigger data update and re-render without tracking where's my component is from RootRender.

So with your suggestion, if there's event submitting from web_sys::EventTarget, it should always happen after manually triggered a microtask right? If that's the case, I think I can improve my current design by separating events into ui | rust-model related | custom web_sys::Event. Thanks again, I'll try and see if I can make this work.

**Comment by extraymond** [comment]
Thanks! It's working now. Queuing it after a microtask works. I'll close this for now. Thanks for your help.
