### ISSUE TITLE
new version publish to crates.io

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#148]
When is in plan to publish the newer version of dodrio to crates.io?
Now the version is 0.1.0 and it doesn't understand async/await.
I would like to publish my crate, but it has a dependency to the newer dodrio.
In development I use the Github/master dependency or path dependency. 
But for publishing a crate, all the dependencies (versions) must be in crates.io.

**Comment by bestia-dev** [comment]
May I temporarily copy/clone dodrio 2 and publish it on crates.io with another temporary name `rust_wasm_dodrio_copy`?
So I can continue my work on crates dependent on dodrio.
When the real dodrio 2 will be published on crates.io, I will just change the dependency.
And remove/yank the temporary crate.

**Comment by fitzgen** [comment]
Published 0.2.0
