### ISSUE TITLE
JSX similar Syntax ?

### ISSUE THREAD

**Issue by luover** [fitzgen/dodrio#22]
JSX similar Syntax  will be nice.

**Comment by fitzgen** [comment]
I don't intend on building JSX syntax into dodrio itself. The idea is that instead one would use [`typed-html`](https://crates.io/crates/typed-html) or something similar, and there would be some integration glue for combining that into dodrio in another crate or something like that. This is part of the "library, not framework" approach mentioned in the README.

**Comment by martijnarts** [comment]
@fitzgen Regarding the "integration glue", should that be a part of dodrio (and should there be an issue to track that), or do you see there being some additional `dodrio-x-typed-html` crate?

**Comment by fitzgen** [comment]
The `typed-html` crate has a feature to enable dodrio support as of this weekend :)

https://github.com/bodil/typed-html/pull/38

**Comment by martijnarts** [comment]
Oh, sick! Forget I said anything :)
