### ISSUE TITLE
Sierpinski triangle example

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/dodrio#29]
It's a common example ever since it was used as a demo for react fiber. We should have an implementation.

**Comment by rylev** [comment]
@fitzgen I'd like to do this. I'll leave issues as I find sharp edges.

**Comment by sseg** [comment]
Sorry to have missed commenting on this earlier. I started an implementation yesterday (PR forthcoming). Perhaps we can collaborate on it @rylev ?

**Comment by rylev** [comment]
No worries! It's still been a good exercise to learn the APIs. I'd definitely like to collaborate!
