### ISSUE TITLE
[feature request] Node::Null

### ISSUE THREAD

**Issue by richard-uk1** [fitzgen/dodrio#47]
Sometimes there is a code path where you don't want to render anything. An example:

```rust
fn render_error(error_msg: Option<&'static str>, bump: &'bump Bump) -> Node<'bump> {
    div(bump)
        .children([
            p(bump).children([text("Some text that is always there")]).finish(),
            match some_state {
                Some(msg) => p(bump).children([text(msg)]).finish(),
                None => Node::Null
            }
        ])
        .finish()
}
```
In this case the vdom sees `Node::Null` and doesn't render anything to the dom. `react` supports returning `null` in javascript for the same effect.
Currently you have to build the children as a `Vec`, which involves mutable state, and is less functionaly :).

**Comment by fitzgen** [comment]
One thing you can do right now is use `filter_map` (or `flat_map`):

```rust
let mut children = bumpalo::collections::Vec::new_in(bump);
children.extend(
    my_maybe_children
        .into_iter()
        .filter_map(|child| if some_predicate(child) {
            Some(p(bump).children([text(child.msg())]).finish())
        } else {
            None
        })
);

div(bump)
    .children(children)
    .collect()
```

**Comment by richard-uk1** [comment]
I've been exploring implementing this: the difficulty is that presently the algorithm for diffing children uses the list of children as slices, and to skip `Node::Null` we need to filter an iterator. I'll keep thinking if there is any other way to implement the diff in the presence of `Node::Null`.

The other arguably even more difficult problem to solve is that of coming up with a good name. It could be `Null`, `Empty`, `Phantom`, etc etc.

**Comment by richard-uk1** [comment]
This is a special case of #119 , where the fragment contains nothing, so I'll close this in favour of that issue.
