### ISSUE TITLE
Can you recommend a Simple http Server written in Rust?

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#50]
In the examples for Dodrio it is suggested to use:
python -m SimpleHTTPServer

I would like to use a Simple http Server written in Rust.
I found many projects on Github, but it is very confusing.
Some are too complex for a simple development Server. Others are incomplete.
I would appreciate if somebody recommends a suitable Simple Server for this use-case.

**Comment by anderejd** [comment]
Here are two alternatives:
 - https://crates.io/crates/https
 - https://crates.io/crates/basic-http-server

At a glance the http server named `https` seems to have more features, but it also has more dependencies. On my current machine `basic-http-server` builds roughly twice as fast as `https` does.

**Comment by bestia-dev** [comment]
Fantastic.
basic-http-server is great for use in development as a simple static file server. 
Just what I need to run Dodrio examples. Maybe it can be suggested in README.md files instead of pythons server.
Thanks.

**Comment by bestia-dev** [comment]
I found your (anderejd) "A minimal wasm-bindgen example" and there you recommended basic-http-server. Great!
I like the idea of not using npm and webpack at all. Keep it super simple. 
Dodrio examples are also without the additional complexity of npm and webpack. I like that.

**Comment by fitzgen** [comment]
The big feature you probably want is for the server to use `application/wasm` as the MIME type for `.wasm` files it serves.

We did some analysis of various simple servers in Rust here: https://github.com/rustwasm/rfcs/pull/10
