### ISSUE TITLE
Game Loop pattern

### ISSUE THREAD

**Issue by johnpmayer** [fitzgen/dodrio#52]
I can't tell if there's a way to create a loop which, for each animation frame, calculates the next state from the current time (provided via the animation frame callback) *and* immediately runs the diff/patch process inside that same animation task.

My use case is a little physics simulator, written in Rust, which would render an SVG document each tick. My initial version in React looks like the below; I've translated it into a psuedo-api that I imagine may be close to dodrio;

```javascript
import { State, VDom } from wasm;

var state = State.initial();
var root = document.getElementById("root");
var vdom = VDom.new(state, root);

function draw(time) { // this is high accuracy provided by requestAnimationFrame
    // Do this inside the animation frame, because we have access to the timestamp
    // This mutates the state value
    state.tick(time);
    // Also do this inside the animation frame (doesn't make sense to wait for the next one)
    // State would implement something like the Render trait
    vdom.renderNow(state);

    requestAnimationFrame(draw);
}

requestAnimationFrame(draw);
```

Is something like this currently possible, or would something need to be exposed? Perhaps said differently, what are your thoughts on exposing a synchronous render function that I can invoke while managing the loop myself from JS? It looks like a lot of this functionality exists (VDomInnerExclusive) but is private.

**Comment by fitzgen** [comment]
Yeah, right now your animation would always have one frame of latency.

> It looks like a lot of this functionality exists (VDomInnerExclusive) but is private.

Exposing a render-something-immediately API is a little tricky because if it is called in an event handler (for example) then the `RefCell` that the component is stored inside is already borrowed, and re-rendering will panic. We could work around this by providing a render-on-the-next-tick-of-the-microtask-queue method. But that is a bit wonky of an API.

I think I'd prefer to expose some sort of raf loop API that takes a `FnMut` closure and runs it one ever frame and then dodrio can safely re-render after invoking that without any fear of re-entrancy. My biggest question here is what the API design might look like and whether it would need to support pausing the loop and if so what taht API would look like (particularly what resumption would be like).

**Comment by johnpmayer** [comment]
Your concerns about a render-immediately api make sense. I can imaging moving that subset of the library (without the dispatcher) to its own create, which leaves the re-entrancy concerns to the user, and then building the current public API atop that. At that point it's significantly less-safe library.

I can imagine the following option for the API in which dodrio "owns" the loop:

A Tick trait with an `update(&mut self, time: f64) -> ()` which would be called inside each render frame. There would be a blanket implementation for a `impl<T: Any + Render + Tick> RootTickRender for T`, which the user would provide to a `pub fn new_loop<RT>(container: &Element, component: R) -> Vdom where RT: RootTickRender`. 

While this has the upside of not requiring users to think about closures (my struggle to articulate the next signature!), this does has the downside of a surprised user when a non-root component's tick function is never called. The alternative is closer to what you suggested, `pub fn new_loop<R, >(container: &Element, component: R, tick: F) -> Vdom where R: RootRender, F: FnMut(f64) -> ()`.

I'm unaware of the *idiomatic* approach to pausing a game loop, but I've seen plenty of implementations that leave pause semantics to the state (would include a `pause: bool`) and the tick (which would continue to run each frame, but would either use a `delta = 0.0` or simply skip making any changes to the state, resulting in a very cheap diff/patch). So I don't think supporting pausing the loop is of large concern.

**Comment by johnpmayer** [comment]
This is a work in progress: https://github.com/fitzgen/dodrio/compare/master...johnpmayer:loop

I think that I was able to move execution time of the Universe.tick() to immediately prior to the diff/patch during the same animation frame.

Thoughts?

**Comment by johnpmayer** [comment]
~~Notably, I think that this could be made even simpler by letting the Render trait's render function take a mutable reference to the component.~~ I think this conflates concerns

After that, providing the loop pattern as implemented in Game Of Life, as part of the Vdom or VdomWeak interface, would be convenient; it's a fairly hairy block of code to understand.

**Comment by johnpmayer** [comment]
After giving this some thought, I feel that this may be poorly motivated. In a scenario where a game loop performs a number of heavy operations (entity-component-systems execution, entity mailbox processing, synchronizing with storage/services, physics) it makes more sense to break these up into separate tasks on the event loop, and then finally render using `vdom.with_component` and `vdom.weak.schedul_render` when appropriate. If any of those heavy steps needs a high performance timestamp, it can already get that using `performance.now()`.

**It's not required that this runs during the animation frame - in fact, it's probably detrimental the more complex and heavy that work becomes, since it's possible to exceed the frame budget!**

My conclusion is that dodrio already provides everything necessary, and probably doesn't need to provide a loop like the one I proposed in #56; in fact any such API is likely to be useful for a toy but overall 

There's perhaps a separate need for a utility to take a sequence of heavy tasks, chain them, and loop them. But that could conceivably exist outside dodrio.
