### ISSUE TITLE
Tutorial for Rust Webassembly/Wasm Virtual Dom Dodrio for webpage, electron and phonegap/cordova

### ISSUE THREAD

**Issue by bestia-dev** [fitzgen/dodrio#55]
I built a super simple memory game for kids in Rust Wasm + Virtual Dom Dodrio. 
The code is on github. 
It can be used as a tutorial how to use the same Rust Wasm code on webpage, electron and PhoneGap.
I would like to here some comments.

https://github.com/LucianoBestia/mem1
https://github.com/LucianoBestia/mem1_website
https://github.com/LucianoBestia/mem1_electron
https://github.com/LucianoBestia/mem1_phonegap

**Comment by MichalObi** [comment]
Look really cool - i'm definitely going to explore your code, specially dodrio usage 
part.

**Comment by bestia-dev** [comment]
Learning Rust and dodrio, I added also mem2, mem3, dodrio_multi_component GitHub projects.
Now I'm working on mem4.
