### ISSUE TITLE
Self mutation for children Node triggered by event.

### ISSUE THREAD

**Issue by extraymond** [fitzgen/dodrio#99]
Hi! I'm new to dodrio and started to like it very much.  I feel like learning dodrio will help me better understand lifetimes, wasm and rust in general.

I have some questions about the behavior of RootRender, and would like to learn more about the design of dodrio.

In the example below, I'm able to trigger mutation.

```rust

struct App {
    count: isize
}

// under impl Render for App
div(bump)
  .on("click", |root, vdom, event| {
    // this one works.
    let handle = root.unwrap_mut::<Self>();
    self.count +=1;
  }).finish()
```

However, I'm getting error when trying to trigger the mutation in a nested node inside App.

```rust

struct App {
   inner: Dummy
}

struct Dummy {}

// under impl Render for Dummy
div(bump)
  .on("click", |root, vdom, event| {
    // next line failed...
    let handle = root.unwrap_mut::<Self>();
  }).finish()

```

I got the error of 
```js
Error: bad `RootRender::unwrap_ref` call
```

For now, If I want to trigger mutation of inner data, It's doable from the parent node event handler. 

---

Here are the questions that I need help getting around.

**1. Access of RootRender**

It seems that RootRender can only be accessed by the root struct. Is there anyway I can trigger an event from a nested struct? Is it necessary to create multiple vdom so they all work independently?

**2. Async mutation with RootRender**

If I wrap my nested data under Rc<RefCell<T>>>, and move my RootRender alongside VdomWeak, I can achieve mutation from an async loop.

```rust
|root, vdom, event| {
let handle = root.unwrap_mut::<Self>();
let fut = async move {
  loop {
    fut_wrap_setTimeout(100).await.unwrap();
    handle.count +=1;
    vdom.schedule_render();
   }
}
spawn_local(fut);
}

```

Although the example above works, I'm curious about how will be better to manage sync/async operations.

Since spawn_local requires 'static lifetime, it's a bit annoying that I have to wrap every data I'm interested to mutate under Rc<RefCell<T>>. What's the proper way to setup program that respect RootRender but able to mutate data underneath it more freely?

Another option I'm considering. Will it be better to go async all the way and create some kinds of async event bus, and handle the mutation and schedule_render over there? If I create an async loop that skips all the time(by always setTimeout for a minimal time), maybe I can do the scheduling there by retrieving events from an async channel that binds to the struct.

Any advice is appreciated. Thx.

**Comment by fitzgen** [comment]
> ```rust
> 
> // under impl Render for Dummy
> div(bump)
>   .on("click", |root, vdom, event| {
>     // next line failed...
>     let handle = root.unwrap_mut::<Self>();
>   }).finish()
> ```

This is failing because `Self` is `Dummy` in this context, and `Dummy` is not the root component. If you did `root.unwrap_mut::<App>()` then it would work. The `root` parameter is always the root of the component tree, not any transitively-called render component.

> Although the example above works, I'm curious about how will be better to manage sync/async operations.

In general, using things like https://docs.rs/futures/0.1.28/futures/sync/mpsc/index.html for most communication will probably make code nicer.

You can also use `VdomWeak::with_component` to get temporary mutable access to the root component when you need to mutate the app state.

**Comment by extraymond** [comment]
Thx for your reply!!! While I'm still absorbing this, it's working now.

Thanks for suggesting mpsc. I'll try to use mpsc to let child send msg back to the root to trigger mutation, since it seems all mutation should be going through root anyway.
